version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
    # volumes it's use for when update any code in src it's directely effect in this service
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    # if somethinf changed in code also update here via this volumes
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    env_file:
      - ./env/mysql.env
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      # PMA_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html/
    command: create-project --prefer-dist laravel/laravel .
  
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    # env_file:
    #   - ./env/mysql.env

volumes:
  mysql-data: